### ISSUE TITLE
Catch Front Matter errors

### ISSUE THREAD

**Issue by gakimball** [zurb/panini#117]
If a YAML error occurs when parsing Front Matter from a page, the parsing step hangs.

```
Parsing pages...Error
    at generateError (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readAlias (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1248:5)
    at composeNode (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1340:20)
    at readBlockMapping (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at Object.load (/Users/geoff/Sites/email-templates/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at parse (/Users/geoff/Sites/email-templates/node_modules/front-matter/index.js:40:27)
```

**Comment by gakimball** [comment]
Implemented in a29fc84cb9297047570bee34df966d0ea327321e
