### ISSUE TITLE
Using lookup helper to invoke partial throws an error

### ISSUE THREAD

**Issue by TheFienix** [zurb/panini#85]
Hi, I'm using handlebar's lookup helper to resolve a partial name based on data

`{{> (lookup data.footer 'template' ) }}`

The partial is working but I'm getting a console error:

`Panini: rendering error ocurred.
 { Error: The partial undefined could not be found
    at Object.invokePartial (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:266:11)
    at Object.invokePartialWrapper [as invokePartial] (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval (eval at createFunctionContext (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-co
mpiler.js:254:23), <anonymous>:11:28)
    at main (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at Object.ret (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at Object.ret [as content] (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at Object.invokePartialWrapper [as invokePartial] (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:72:46) at Object.eval (eval at createFunctionContext (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-co
mpiler.js:254:23), <anonymous>:6:28)
    at main (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at Object.invokePartial (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:268:12)
    at Object.invokePartialWrapper [as invokePartial] (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:68:39)
    at Object.eval (eval at createFunctionContext (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-co
mpiler.js:254:23), <anonymous>:10:28)
    at main (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/user/project/node_modules/panini/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: 'The partial undefined could not be found',
  name: 'Error',
  number: undefined }`

**Comment by mcblum** [comment]
@TheFienix I don't suppose you ever figured this out?
